Algoritmo "a"
// Disciplina   : Algoritmos Manzano (5.6.1)
// Professor   : Jailson 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Murilo
// Data atual  : 01/10/2023
Var
// Seção de Declarações das variáveis 

i: inteiro
Quadrado: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Para i <- 15 Ate 200 Passo 1 Faca

Quadrado <- i ^ 2

Escreval(Quadrado)

Fimpara

Fimalgoritmo